### ISSUE TITLE
Troubleshoot intermittent Maximum call stack size exceeded error for bootstrap select

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-northwest-js#10]
I suspect this has something to do with the new version of the bootstrap select having bugs.

![image](https://user-images.githubusercontent.com/2495167/44736512-0d13bd00-aab5-11e8-842c-0d2b257513df.png)

**Comment by HansVraga** [comment]
@rstevensonUSGS See if you can recreate this error, if you can replicate, etc.

**Comment by rstevensonUSGS** [comment]
Documented the troubleshooting I conducted for this issue here: https://drive.google.com/open?id=17yUvrcOHcppBAV6Djn-SD2mgp7v-hG2O

**Comment by rstevensonUSGS** [comment]
What is the nest step in this process? for getting this taken cared of?.

**Comment by esmyers** [comment]
boostrap-select v 1.13.2 causes the bug.  Upgraded to bootstrap-select 1.13.3
