### ISSUE TITLE
AWS redirect from old SPARROW URLs to new ones

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-northwest-js#45]
I had to change the production URLs for some applications.  Please set up the following redirects in AWS.  The first URL in each item should redirect to the second URL that contains the year.

- https://sparrow.wim.usgs.gov/california/ -->   https://sparrow.wim.usgs.gov/sparrow-california-2002/

- https://sparrow.wim.usgs.gov/east-us/ --> https://sparrow.wim.usgs.gov/sparrow-east-2002/

- https://sparrow.wim.usgs.gov/pacific-northwest/ --> https://sparrow.wim.usgs.gov/sparrow-pacific-northwest-2002/ 

- https://sparrow.wim.usgs.gov/national-dissolved-solids/ --> https://sparrow.wim.usgs.gov/sparrow-national-dissolved-solids-2000/

Thanks and let me know if you have questions!

**Comment by aaronstephenson** [comment]
Implemented as S3 Metadata redirects (https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html#page-redirect-using-console)
