### ISSUE TITLE
check phosColors and nitroColors in config to make sure they line up with sources

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-northwest-js#7]
1.  Make sure the number of hex keys match number of sources
2.  Make sure the colors are in the right order.

**Comment by rstevensonUSGS** [comment]
Corrected the TN for developed land. Reviewed the rest of the colors, for entrys that are  came in TN and TP colors match. the entiers. Last three enteries in TN have the last three colors in the color document. 
#00a900 - Green 
#006800 - Dark Green 
#0070C0- Blue
